#!/usr/bin/env ruby

root = File.expand_path(File.dirname(File.dirname(File.dirname(__FILE__))))
Dir.chdir(root)

require File.join(root, "config", "environment")

loop do
  FeedWorker.update('main_feeds')
  sleep 5
end
