#!/usr/bin/env ruby

root = File.expand_path(File.dirname(File.dirname(File.dirname(__FILE__))))
Dir.chdir(root)

require File.join(root, "config", "environment")

$running = true
Signal.trap("TERM") do
  $running = false
end

# Run the FeedWorker in
while($running) do
  FeedWorker.update_all
  sleep 5
end
