#!/usr/bin/env ruby

root = File.expand_path(File.dirname(File.dirname(File.dirname(__FILE__))))
Dir.chdir(root)

require File.join(root, "config", "environment")

loop do
  FeedWorker.update(Feed.where.not(category: 'my_own'), 'main', feed_pause: 1)
  sleep 5
end
