#!/bin/bash
#
# Install as /etc/init.d/dashboard-god
#
# god       Startup script for god (http://god.rubyforge.org)
#
# chkconfig: - 85 15
# description: God is an easy to configure, easy to extend monitoring \
#              framework written in Ruby.
#

RETVAL=0

GOD=/usr/local/bin/god
GOD_SCRIPT=/var/www/dashboard/daemons.god

case "$1" in
    start)
      $GOD -P /var/run/god.pid -l /var/log/god.log
      $GOD load $GOD_SCRIPT
      RETVAL=$?
      ;;
    stop)
      $GOD terminate
      RETVAL=$?
      ;;
    restart)
      $GOD terminate
      $GOD -P /var/run/god.pid -l /var/log/god.log
      $GOD load /var/www/dashboard/daemons.god
      RETVAL=$?
      ;;
    status)
      $GOD status
      RETVAL=$?
      ;;
    *)
      echo "Usage: god {start|stop|restart|status}"
      exit 1
  ;;
esac

exit $RETVAL